version: "3.8"

services:


  server:
    container_name: server
    build: ./server
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - data:/data
    environment:
      - DB_URL=/data/sqlite.db
      - TIME_ADDITION_MS=200
      - TIME_SUBTRACTION_MS=200
      - TIME_MULTIPLICATION_MS=800
      - TIME_DIVISION_MS=800
    networks:
      - calc-net

  agent:
    container_name: agent
    build: ./agent
    environment:
      - SERVER_URL=http://server:8080
      - COMPUTING_POWER=5
      - TIME_WAIT_MS=1000
      - SERVER_GRPC=server:50051
    networks:
      - calc-net
    depends_on:
      - server

  web:
    container_name: web
    build: ./web
    ports:
      - "8081:80"
    depends_on:
      - server
    networks:
      - calc-net

volumes:
  data:

networks:
  calc-net:
    driver: bridge
