version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - calc-net
    environment:
      - TIME_ADDITION_MS=200
      - TIME_SUBTRACTION_MS=200
      - TIME_MULTIPLICATION_MS=800
      - TIME_DIVISION_MS=800

  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    networks:
      - calc-net
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:8080
      - COMPUTING_POWER=5
      - TIME_WAIT_MS=1000

networks:
  calc-net:
    driver: bridge