swagger: "2.0"
info:
  version: 1.0.0
  title: Distributed Calculator API
  description: API for distributed calculation of arithmetic expressions with user authentication and persistent storage
host: localhost:8080
basePath: /api/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  BearerAuth:
    type: apiKey
    name: Authorization
    in: header
paths:
  /calculate:
    post:
      security:
        - BearerAuth: []
      tags:
        - Expressions
      summary: Submit new expression for calculation
      parameters:
        - in: body
          name: input
          required: true
          schema:
            $ref: '#/definitions/CalculateRequest'
      responses:
        201:
          description: Expression accepted
          schema:
            $ref: '#/definitions/CalculateResponse'
          examples:
            application/json:
              id: 550e8400-e29b-41d4-a716-446655440000
        400:
          description: Invalid input format
        401:
          description: Unauthorized
        422:
          description: Unprocessable expression
          schema:
            $ref: '#/definitions/ErrorResponse'
  /expressions:
    get:
      security:
        - BearerAuth: []
      tags:
        - Expressions
      summary: Get all user's expressions
      description: Returns list of all expressions with their current statuses
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/ExpressionsList'
        401:
          description: Unauthorized
  /expressions/{id}:
    get:
      security:
        - BearerAuth: []
      tags:
        - Expressions
      summary: Get expression by ID
      description: Returns detailed information about specific expression
      parameters:
        - in: path
          name: id
          required: true
          type: string
          format: uuid
          description: ID of the expression to return
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/ExpressionDetails'
        401:
          description: Unauthorized
        404:
          description: Expression not found
          schema:
            $ref: '#/definitions/ErrorResponse'
definitions:
  CalculateRequest:
    type: object
    required:
      - expression
    properties:
      expression:
        type: string
        example: (2+3)*4/5
        description: Arithmetic expression to calculate
  CalculateResponse:
    type: object
    properties:
      id:
        type: string
        format: uuid
        example: 550e8400-e29b-41d4-a716-446655440000
        description: Unique identifier for the expression
  ExpressionDetails:
    type: object
    properties:
      id:
        type: string
        format: uuid
        example: 550e8400-e29b-41d4-a716-446655440000
      expression:
        type: string
        example: 2+2*2
      status:
        type: string
        enum:
          - pending
          - processing
          - completed
          - failed
        example: completed
      result:
        type: number
        format: float
        example: 6
      created_at:
        type: string
        format: date-time
        example: '2023-05-15T10:00:00Z'
      updated_at:
        type: string
        format: date-time
        example: '2023-05-15T10:00:05Z'
  ExpressionsList:
    type: object
    properties:
      expressions:
        type: array
        items:
          $ref: '#/definitions/ExpressionDetails'
  ErrorResponse:
    type: object
    properties:
      error:
        type: string
        example: Division by zero
      details:
        type: string
        example: Expression contains division by zero at position 15
      timestamp:
        type: string
        format: date-time
        example: '2023-05-15T10:00:00Z'