services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile.test
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - DB_DSN=file::memory:?cache=shared
      - JWT_SECRET=test-secret


  tests:
    container_name: tests
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - orchestrator
    volumes:
      - ./tests:/app/tests
    command: ["go", "test", "-v", "./tests/integration/..."]